spring:
    datasource:
        url: jdbc:mysql://192.168.1.216:3306/securecapita
        password: letmein
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                globally_quote_identifier: true
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    sql:
        init:
            mode: never
